### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by alexisju** [Salandora/OctoPrint-FileManager#16]
On a fresh install (Octopi/Octoprint 1.3.8 and FileManager 0.1.2), i had an issue where nothing (no one file) is displayed until i choose to set _Sort > Mixed_

If i turn back default setting _Sort > By Files / By Folders_ or _By Folders / By Files_, the listing goes empty again.

**Comment by Henry0191** [comment]
Same problem here

**Comment by christianlupus** [comment]
I can confirm this.

![vokoscreen-2018-06-22_14-39-39](https://user-images.githubusercontent.com/8202922/41777341-3f973c0c-762b-11e8-8086-6ca419a62c1a.gif)

**Comment by MichMich** [comment]
Can confirm.

**Comment by Salandora** [comment]
Should be fixed with bug fix release 0.1.3
Please report back.

**Comment by pauln** [comment]
0.1.3 does indeed seem to have fixed it for me - thanks for the release!

**Comment by christianlupus** [comment]
Thanks, that seems to solved the problem.

**Comment by alexisju** [comment]
Fixed :) Thank you!
