### ISSUE TITLE
Folders not showing up

### ISSUE THREAD

**Issue by IdefixRC** [Salandora/OctoPrint-FileManager#19]
Filemanager 0.1.2 -> no folders are showing up.
Understand there is a bug with the general view (need to set to mixed to see files) but even then no folder is showing up.

**Comment by Salandora** [comment]
Hi,

can you please test it with the current bug fix release,
I tried it myself and can see the folders, so I hope it will have fixed it for you too.
Please report back if it is working now

**Comment by IdefixRC** [comment]
Thanks. I can confirm that it works now. Thanks for the fix
