### ISSUE TITLE
No cost per print information displayed

### ISSUE THREAD

**Issue by 2987ms** [Salandora/OctoPrint-FileManager#20]
Using the latest versions of OctoPrint (1.3.8) and the latest version of Filament Manager (0.5.3), I have no cost per print function. Brand new install of OctoPrint

**Comment by Salandora** [comment]
Could you post a screenshot highlighting where you would expect it?
I assume you want it to be inside the file manager itself, which might be a bit problematic, this would need to be done in the Filament Manager code, while I need to provide some way for it to add additional data.

**Comment by 2987ms** [comment]
I'm an idiot, I'm on the wrong GitHub, sorry Salandora.
