### ISSUE TITLE
[Feature request] Add checkbox + select all checkbox

### ISSUE THREAD

**Issue by madmax2** [Salandora/OctoPrint-FileManager#23]
Would be good if the file manager added checkbox column (before the NAME column) for all the files listing and a checkbox at the very top that when we click that, it will SELECT ALL files..

This would make selection of lots of files more faster than current method.

**Comment by Salandora** [comment]
Checkbox before NAME is implemented in 0.1.6.
I decided for a SELECT ALL and DESELECT ALL button instead of a checkbox.
