### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by Nickjallday** [Salandora/OctoPrint-FileManager#25]
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by AlexVerrico** [comment]
Hi @Nickjallday 
I have created a pull request (#26) to add support for Python 3 to this plugin.
Until @Salandora merges this pull request, the updated version can be installed from https://github.com/AlexVerrico/OctoPrint-FileManager/archive/master.zip
Cheers,
Alex.

**Comment by Salandora** [comment]
Thanks to @AlexVerrico the 0.1.4 version should be python 3.6 compatible now.
