### ISSUE TITLE
"%" symbol in folder and file names does not display in FileManager

### ISSUE THREAD

**Issue by Vic-Y** [Salandora/OctoPrint-FileManager#27]
When folder or file names have the "%" symbol, the "%" symbol does not display correctly in FileManager (although the names appear correctly in the standard OctoPrint Side Bar.

![image](https://user-images.githubusercontent.com/62916399/83588758-4a6d7000-a50f-11ea-8e52-48581ad3c8e3.png)

**Comment by Salandora** [comment]
Nice catch,

I'll look into that as soon as possible.

**Comment by Salandora** [comment]
Should finally be fixed in 0.1.6.
