### ISSUE TITLE
Table Layout messed up

### ISSUE THREAD

**Issue by bitboy85** [Salandora/OctoPrint-FileManager#29]
The Column separators are wrong for the listet files.
The created column has no space and the size (größe) column "cuts" into the text.

![columns](https://user-images.githubusercontent.com/6197580/90866392-1d08c380-e394-11ea-9c5f-39c13f0a67d8.png)

**Comment by KeltE** [comment]
Hello! Is there any way to fix scrambled lines?
Thank you! Egon
![Failmanager plugin mixed lines](https://user-images.githubusercontent.com/66703581/97024558-9d4bd080-155f-11eb-975b-fa32b905a938.png)

**Comment by Salandora** [comment]
Working on a solution right now.

**Comment by Salandora** [comment]
Should finally be fixed in 0.1.6.
