### ISSUE TITLE
long gcode filenames intrude into the "created" column

### ISSUE THREAD

**Issue by ntoff** [Salandora/OctoPrint-FileManager#3]
https://youtu.be/qzLp7AGBrMg

gcode files with long names will intrude into the "created" column and hovering over it will truncate the name.

Octoprint Version: 1.3.0 (master branch)
FileManager (0.1.1)

**Comment by Salandora** [comment]
Ohh good spot, will take a look at it.

**Comment by ntoff** [comment]
I guess for the record, this is the name of the gcode file in full 3DBenchy.ABS_Katie.03hx054w_02fill_45EL.gcode in case it matters, like if having more than one period in it messes up the ability to figure out what is and isn't a filetype extension or something.

**Comment by Salandora** [comment]
Should finally be fixed in 0.1.6.
