### ISSUE TITLE
Vote for Thumbnails

### ISSUE THREAD

**Issue by Jack77777777** [Salandora/OctoPrint-FileManager#36]
Is it possible to show thumbnails from https://plugins.octoprint.org/plugins/prusaslicerthumbnails/ in this plugin?

**Comment by Salandora** [comment]
Will look into that. Seems interesting.

**Comment by mediocre-to** [comment]
+1 on thumbnails.

**Comment by MrDragon420** [comment]
This would be really nice

**Comment by pboucher14** [comment]
add my vote for thumbnails

**Comment by Salandora** [comment]
Implemented in Version 0.1.7rc1 for now, it will get improved in rc2 as I realized some more options would be helpful and less annoying.
