### ISSUE TITLE
Cut and Paste Leaves Almost-Empty File in Original Location

### ISSUE THREAD

**Issue by cr45hmurphy** [Salandora/OctoPrint-FileManager#37]
Cut and Paste function works as expected. However, 130.0 byte file, with same name, is left in original location. See screenshots.

![filemanager1](https://user-images.githubusercontent.com/4840152/106757786-65403900-65f6-11eb-8b92-0919311c4683.PNG)
![filemanager2](https://user-images.githubusercontent.com/4840152/106757788-6709fc80-65f6-11eb-8621-3cdad154cdbe.PNG)

**Comment by cr45hmurphy** [comment]
Going to close this issue. Appears that this is an issue with the [GCodeEditor](https://github.com/ieatacid/OctoPrint-GcodeEditor) plugin.

**Comment by cr45hmurphy** [comment]
Can we reopen this issue, please? I thought I had isolated the issue to the GCodeEditor plugin, but that does not seem to be the case. It may be an issue with both of these plugins.

**Comment by cr45hmurphy** [comment]
I thought I had isolated the issue to the GCodeEditor plugin, but that does not seem to be the case. It may be an issue with both of these plugins.

**Comment by OllisGit** [comment]
Just for the records: Should be fixed in latest DLP release 1.25.4
